#!/bin/sh

BASEURL="$1"
TMPFILE="testing/page"

run_test() {
	echo -n "$1... "
	eval "$2" && echo pass && return
	echo FAIL
	exit 1
}

fetch_page() {
	run_test "Fetching $1 $2" 'curl -is "'"$2"'" > "$TMPFILE"'
}

check_status() {
	run_test "Checking status code $1" \
	'grep -q "^HTTP/[0-9.]* '"$1"'" "$TMPFILE"'
}

fetch_page 'test page' "$BASEURL/hello"
check_status 200
run_test "Checking mainpage content" 'grep -q "Hello World" "$TMPFILE"'
fetch_page 'search' "$BASEURL/api/v1/search?long=24.93545&lat=60.16952"
check_status 200
run_test "Checking query points" 'grep -q "24.93545,60.16952" "$TMPFILE"'
run_test "Checking query tags" 'grep -q "capital" "$TMPFILE"'
fetch_page 'limit search' "$BASEURL/api/v1/search?long=0&lat=0&limit=1"
check_status 200
run_test "Checking only one response given" \
  'test X`grep -o "coord" "$TMPFILE" | wc -l` = X1'
fetch_page 'invalid search' "$BASEURL/api/v1/search?limit=52"
check_status 400
run_test "Checking response is JSON" \
  'grep -qi "^content-type: application/json" "$TMPFILE"'
fetch_page 'nonexistent call' "$BASEURL/api/v1/foobar"
check_status 404
run_test "Checking response is JSON" \
  'grep -q "error. *: *.this API call" "$TMPFILE"'
run_test "Removing temporary file" 'rm "$TMPFILE"'

