#!/bin/bash

test -z "$*" && echo "Give issue summary on command line" && exit 1
test -z "$EDITOR" && EDITOR=sensible-editor

git stash -q --keep-index

NUMBER=`ls issues | grep '^[0-9]\{4\}-' | tail -1 | cut -d- -f1` 
FILE="issues/`expr $NUMBER + 1`-`echo "$@" | tr ' ' '-'`"
echo 'description: ' > "$FILE"
if test -t 0; then
	"$EDITOR" "$FILE" 
else
	sed 's/^/    /' >> "$FILE"
fi

git add "$FILE" && git commit -m "$FILE"

git stash pop -q

